config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  get '/about', to: 'pages#about'

  devise_for :users

  get 'root' => 'flat#show'
  get 'landing/index' => 'landing#index'
  match '/admin', to: 'admin/flats#index', via: :get
  get 'about', to: 'pages#about'
  resources :flats, only: [:index, :show, :edit, :update]
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  ActiveAdmin.routes(self)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  #attribute :nickname,  :captcha  => true
  after_create :send_welcome_email

  # def headers
  #   {
  #     :subject => "Contact Form",
  #     :to => "contact@ezi-x.com",
  #     :from => %("#{name}" <#{email}>)
  #   }
  # end


  private

  def send_welcome_email
    ContactMailer.welcome(self).deliver_now
  end
end

app/models/flat.rb
class Flat < ApplicationRecord

  belongs_to :user
  belongs_to :page

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :flat
  mount_uploader :image, PhotoUploader
end

app/models/page.rb
class Page < ApplicationRecord
  has_many :flat
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :flat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new
    #@contact.request = request
    if @contact
      ContactMailer.welcome(@contact).deliver_now
      # redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [ :show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!

  def index
    @flats = Flat.all
    #@leases = Lease.all
  end

  def show
    @hash = Gmaps4rails.build_markers(@flat) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def new
    @flat = Flat.new.user_id
    @image = @flat_id.images.build
  end

  def create
    @flat = Flat.new flat_params
  end

  def edit
  end

  def update
    respond_to do |format|
      if @flat.update(flat_params)
        if params[:images]
          params[:images].each do |image|
            @flat.images.create(image: image)
          end
        end
        format.html { redirect_to @flat, notice: 'Photos was successfully uploaded.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @flat.destroy
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.permit(
      :property_type,
      :price,
      :bedroom_number,
      :square_meters,
      :room_number,
      :description,
      :opinion,
      :bathroom,
      :wc,
      :floor,
      :terrace,
      :cellar,
      :transports,
      :around_description,
      :environment,
      :transport,
      :school,
      :shop,
      :bus,
      :metro,
      :address,
      images_attributes: [:image, :flat_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
    @flats = Flat.where.not(latitude: nil, longitude: nil)
    @hash = Gmaps4rails.build_markers(@flats) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
      marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    @user = current_user
  end

  def edit
    @user.edit user_params
  end

  def update
    @user.update user_params
  end

  def destroy
    @user.destroy
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :admin, :encrypted_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/create.html.erb
<div class="container">
  <div class="row background-box">
    <div class="background-box col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1  ">
      <div class="skinny_wrapper wrapper_padding text-center">
        <h1>Merci pour votre message! </h1>
        <p>Nous revenons vers vous au plus vite.</p>
      </div>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class=" col-xs-12 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 contact-background-box text-center">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <div align="center">
          <h3 style="font-weight: bold; margin-top: -10px">VOTRE MESSAGE</h3>
          <p style="margin-bottom: 20px;">Nous vous contacterons au plus vite.</p><br>
          <%= form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
            <%= f.text_field :name, placeholder: "Nom Prénom", :required => true %>
            <%= f.email_field :email,placeholder: "Email", label: false, :required => true %>
            <p style="font-weight: bold; text-align: left; margin-top: -7px" >Objet:</p>
            <%= select_tag(:object, options_for_select(
              [
                ["Demande d'estimation", 1],
                ["Demande de visite", 2, ],
                ["Demande de bien spécifique", 3, ],
                ["Autre", 4, ]

              ],
            ), { :class => 'adjust-input', :include_blank => "Choisir un objet" }) %>

            <p style="font-weight: bold; text-align: left; margin-top: 15px">Message:</p>
            <%= f.text_area :message, :as => :text, placeholder: "Recherche un appartement dans le 3ème avec vue sur parc...", label: false, :required => true %>
            <div class= "hidden">
              <%#= f.text_field :nickname, :hint => 'Leave this field blank!' %>
            </div>
              </br>
              <%= f.submit 'ENVOYER', class: "pages-cta-light-form" %>
            </div><br>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/_map_box.html.erb
<div class="map_box">
  <h3><%= flat.property_type %></h3>
  <p><%= flat.description %></p>
  <p><%= flat.price %> €</p>

  <%= link_to "Voir", flat_path(flat), class: "btn-map-box text-center" %>
</div>

app/views/flats/edit.html.erb
<div class="container">
  <div class="row col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 contact-background-box text-center">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2">
      <h1 style="font-weight: bold">Photo Uploader</h1>
      <div class="card-form">
        <br>
        <br>
        <%= form_for(@flat, :html => { multipart: true }) do |f| %>
          <%= f.fields_for :image do |ff| %>
              <div class="field">
                <h3 style="text-align: left;"><%= ff.label :image %>:</h3><br><br><br>
                <%= ff.file_field :image, multiple: true, name: "images[]" %>
              </div><br><br><br>
            <% end %>
          <%= f.submit 'UPLOAD', class: "pages-cta-light-form"%>
          <br>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <p class="above-background-box"> Vous recherchez un bien spécifique, <%= link_to "nous vous informons avant mise en ligne.", contacts_path, class: "text-link"%></p>
  <div class="row background-box">
    <h4 class="cards-header"><%= @flats.count %> biens immobiliers actuellement en vente</h4>
    <div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <%= render "shared/flat_card" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container">
  <div class="row background-box" style="padding-top: 0px">
    <div class="sub-navbar">
      <div class="col-xs-12 col-md-12 ">
        <% if user_signed_in? && current_user.admin %>
          <h3><%= @flat.property_type %></h3>
          <%= link_to "Image Upload", edit_flat_path(@flat), class:"btn-upload" %>
        <% else %>
        <h3><%= @flat.property_type %></h3>
        <ul class="list-inline text-center show-flat-list">
          <li style="border-right:1px solid $light-grey;">
            <%= image_tag "bed.png", class:"show-bed-icon-size" %>
            <strong><p><%= @flat.bedroom_number %> Chambre(s)</p></strong>
          </li>
          <li style="border-right:1px solid $light-grey;">
            <%= image_tag "ruler.png", class:"show-ruler-icon-size" %>
            <strong><p><%= @flat.square_meters %> Mètres Carrés</p></strong>
          </li>
          <li>
            <%= image_tag "door.png", class:"show-door-icon-size" %>
            <strong><p><%= @flat.room_number %> Pièce(s)</p></strong>
          </li>
        </ul>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-12 ">
      <!-- Caroussel -->
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <% @flat.images.each_with_index do |image, index| %>
            <li data-target="#carousel-example-generic" data-slide-to="<%= index %>" class="<%= index == 0 ? "active" : "" %>"></li>
          <% end %>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner" id='gradient' role="listbox">
          <% @flat.images.each_with_index do |image, index| %>
            <div class="item <%= index == 0 ? "active" : "" %>" style="background-image:url('<%= asset_url image.image_url(:flat_show) %>');background-size: cover;background-position:center center;height:600px;">
            </div>
          <% end %>
        </div>
         <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <div class="col-xs-12 col-md-12 ">
    <div class="wrapper-description">
      <div class="border-box" style="padding: 0px">
        <div class="subtitle-border">
          <h4>Description</h4> <h4><%= @flat.price %> €</h4>
        </div>
        <div class="characteristics">
          <div class="row">
            <div class="col-xs-6 text-position">
              <li><%= @flat.bathroom %></li>
              <li><%= @flat.wc %></li>
              <li><%= @flat.terrace %></li>
            </div>
            <div class="col-xs-6 text-position">
              <li><%= @flat.heating %></li>
              <li><%= @flat.floor %></li>
              <li><%= @flat.cellar %></li>
            </div>
          </div><br>
          <p><%= @flat.around_description %></p>
        </div>
      </div>


      <div class="flat-opinion">
        <div class="border-box" style="padding: 0px">
          <div class="subtitle-border">
            <h4>Notre Avis</h4>
          </div>
          <div class="text-opinion text-justify">
            <p><%= @flat.opinion %></p>
          </div>
        </div>
      </div>

      <div class="border-box" style="padding: 0px">
          <div class="subtitle-border">
            <h4>Environnement</h4>
          </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-4">
              <div class="text-info">
                <h4>Transports</h4>
                <p><%= @flat.metro %></p>
                <p><%= @flat.bus %></p><br>
                <h4>Ecoles</h4>
                <p><%= @flat.school %></p><br>
                <h4>Commerces</h4>
                <p><%= @flat.shop %></p>
              </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-8">
              <div class="map-position">
                <div id="map" style="width: 100%; height: 400px;"></div>

                <% content_for(:after_js) do %>
                  <script>
                    $(document).ready(function() {
                      var handler = Gmaps.build('Google');
                      handler.buildMap({ internal: { id: 'map' } }, function() {
                        markers = handler.addMarkers(<%= raw @hash.to_json %>);
                        handler.bounds.extendWith(markers);
                        handler.fitMapToBounds();
                        if (markers.length == 0) {
                          handler.getMap().setZoom(3);
                        } else if (markers.length == 1) {
                          handler.getMap().setZoom(14);
                        }
                      });
                    });
                  </script>
                <% end %>
              </div>
            </div>
          </div>
      </div><br><br><br>

      <div class="text-center">
        <div class="col-xs-12 col-sm-6 call-to-action">
        <%= link_to "JE VISITE", contacts_path, class:"pages-cta" %>
        </div>
        <div class="col-xs-12 col-sm-6 call-to-action">
        <%= link_to "RETOUR", flats_path, class:"pages-cta-light" %>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag "favicon.ico"%>
    <title>EZI-X</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body class="Site">
    <main class="site-content">
      <% if controller_name !='pages' %>
      <%= render 'shared/navbar'%>
      <% else %>
      <%= render 'shared/home_navbar'%>
      <% end %>
      <%= render 'shared/flashes' %>
        <%= yield %>

      <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
      <%#= javascript_include_tag "https://maps.google.com/maps/api/js" %>
      <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
      <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

      <%= javascript_include_tag "application" %>
      <%#= cloudinary_js_config %>
    </main>
    <%= render 'shared/footer' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="wrapper">
  <div class="position-caroussel">
    <div class="col-xs-12 col-sm-6 col-md-4 hover-slide text-center">
      <ul>
        <li><%= link_to "NOS BIENS", flats_path, class: "btn-home"%> </li><br>
        <i class="fa fa-chevron-right position-1" aria-hidden="true"></i>

        <li><%= link_to "CONTACT", contacts_path, class: "btn-home" %></li>
        <i class="fa fa-chevron-right position-2" aria-hidden="true"></i>

        <li><%= link_to "EQUIPE", about_path, class: "btn-home" %></li>
        <i class="fa fa-chevron-right position-3" aria-hidden="true"></i>
      </ul>
    </div>
    <div id="carousel-example-generic" class="carousel-home slide" data-ride="carousel">
      <!-- Wrapper for slides -->
      <div class="carousel-inner inner-size" id='gradient' role="listbox">
        <div class="item active">
          <%= image_tag("home-1.jpg", :alt => "home-pic") %>
        </div>
        <div class="item">
          <%= image_tag("home-chair.jpg", :alt => "home-chair") %>
        </div>
        <div class="item">
          <%= image_tag("home-salon.jpg", :alt => "home-salon") %>
        </div>
      </div>
    </div>
  </div>
  <!-- Info -->
  <div class="background-style">
  <h1 class="text-center">L’agence ERA Cambronne devient EZI-X!</h1><br><br>
  <div class="row">
    <div class="col-xs-12">
      <div class="col-xs-12 col-sm-4">
        <div class="text-center box-style">
          <%= image_tag("Preparation-vente.jpg", :alt => "Preparation-vente", class:"sizing-img") %>
          <h4>Préparation de la vente</h4>
          <p>Estimation au juste prix</p>
          <p>Marketing du bien</p>
          <p>Préparation du dossier de vente</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="text-center box-style">
          <%= image_tag("recherche_acquereur.jpg", :alt => "recherche_acquereur", class:"sizing-img") %>
          <h4>Recherche des acquéreurs</h4>
          <p>Prise en charge des visites</p>
          <p>Activation de notre base acquéreurs</p>
          <p>Vérification de solvabilité</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="text-center box-style">
          <%= image_tag("Signature_acte.jpg", :alt => "Signature_acte", class:"sizing-img") %>
          <h4>Signature de l’acte de vente</h4>
          <p>Communication des pièces au notaire</p>
          <p>Aide à la recherche de solutions</p>
          <p>déménagement et de travaux</p>
        </div>
      </div><br><br><br>
      <div class="col-xs-12 text-center main-trait">
        <h2>TRANSPARENCE & REACTIVITE </h2>
        <p>______________</p>
        <h2 id="title-home">COMMISSIONS ATTRACTIVES</h2>
      </div>
    </div><br><br><br>

  </div>
  </div>
  <!-- Map -->
  <div>
    <div id="map" class="map-home-size"></div>
    <% content_for(:after_js) do %>
      <script>
        $(document).ready(function() {
          var handler = Gmaps.build('Google');
          handler.buildMap({ internal: { id: 'map' } }, function() {
            markers = handler.addMarkers(<%= raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            if (markers.length == 0) {
              handler.getMap().setZoom(3);
            } else if (markers.length == 1) {
              handler.getMap().setZoom(14);
            }
          });
        });
      </script>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<div class="p-design">
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>
</div>

app/views/shared/_flat_card.html.erb
<% @flats.each do |flat| %>
  <%= link_to flat_path(flat), class:'card-link-default' do %>
    <div class="flat-card">
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 padding-pic">
        <div class="flat-pic" style="background-image: url('<%= asset_url(flat.images.empty? ? "home-chair.jpg" : flat.images.first.image_url(:flat_show)) %>');"></div>
      </div>
      <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
        <div class="dp-content">
          <address class="type-title">
            <strong><h3><%= flat.property_type %></h3></strong>
          </address>
          <p class="flat-price"><%= flat.price %> €</p>
        </div>
        <p class="flat-description"><%= flat.description %> </p>
        <ul class="list-inline text-center flat-list">
          <li style="border-right:1px solid $light-grey;">
            <%= image_tag "bed.png", class:"bed-icon-size" %>
            <strong><p><%= flat.bedroom_number %> Chambre(s)</p></strong>
          </li>
          <li style="border-right:1px solid $light-grey;">
            <%= image_tag "ruler.png", class:"ruler-icon-size" %>
            <strong><p><%= flat.square_meters %> Mètres Carrés</p></strong>
          </li>
          <li>
            <%= image_tag "door.png", class:"door-icon-size" %>
            <strong><p><%= flat.room_number %> Pièce(s)</p></strong>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-social-link">
    <ul class="list-inline">
      <li>
        <a href="https://www.facebook.com/EZIXimmo" target=_blank>
          <i class="fa fa-facebook-square fa-home"></i>
        </a>
      </li>
      <li>
        <a href="https://twitter.com/EZIXimmo" target=_blank>
          <i class="fa fa-twitter fa-home"></i>
        </a>
      </li>
      <li>
        <a href="#" target=_blank>
          <i class="fa fa-linkedin fa-home"></i>
        </a>
      </li>
    </ul>
  </div>
  <div class="footer-newsletter form-inline">
    <label for="" style="color: white; font-weight: lighter;margin-bottom: -4px!important; margin-right: 80px !important;margin-top: 10px" >Souscrivez à la newsletter:</label>

    <div class="sendgrid-subscription-widget email-input" data-token="ffedCO4%2FbVU5m3zAWJVWD%2F4rLboqvlp47Kb9k24N7TZS3uSUA92eoVZVUq%2Fvf0Y9SD7uBpArOeTMiH9TEnu6dQ%3D%3D" data-submit-text="Suivez-nous" data-message='false'>
    </div>
    <script>
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?"http":"https";
    if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://s3.amazonaws.com/subscription-cdn/0.2/widget.min.js";fjs.parentNode.insertBefore(js,fjs);}}(document, "script", "sendgrid-subscription-widget-js");
    </script>
  </div>
</div>

app/views/shared/_home_navbar.html.erb
<div class="navbar-wagon-home">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <h1 class="navbar-logo">EZI-X <span style="font-weight: lighter; font-size: 25px">immo</span></h1>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? && current_user.admin %>
    <%= link_to "Dashboard", admin_flats_path, class: "navbar-wagon-item navbar-wagon-link-admin " %>
     <i class="fa fa-phone" aria-hidden="true" style="color: white; font-size: 15px;"><span class="fix-font">   +33 1 43 06 04 00</span> </i>
    <%= link_to "Qui sommes nous ?", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% else %>
    <h4 style="color: white; margin-right: 30px; font-weight: lighter;">"Site actuellement en construction"</h4>
    <i class="fa fa-phone" aria-hidden="true" style="color: white; font-size: 15px;"><span class="fix-font">   +33 1 43 06 04 00</span> </i>
    <%#= link_to "Qui sommes nous ?", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>


  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Qui sommes nous ?", about_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%#= link_to "Contact", contacts_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand-home" do %>
    <h1 class="navbar-logo">EZI-X <span style="font-weight: lighter; font-size: 25px;">immo</span></h1>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <i class="fa fa-phone" aria-hidden="true" style="color: white; font-size: 15px;"><span class="fix-font"> +33 1 43 06 04 00</span> </i>
    <%= link_to "Qui sommes nous ?", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
  </div>


  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Qui sommes nous ?", about_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%#= link_to "Contact", contacts_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>